global: {}

# -- vc-authentication sub-chart parameters (https://github.com/FIWARE/vc-authentication)
vcAuthentication:
  enabled: true

# -- odrl-authorization sub-chart parameters (https://github.com/fiware/odrl-authorization)
odrlAuthorization:
  enabled: true