name: Check Chart Dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 2'

jobs:

  check-dependencies:
    name: "Check dependent chart versions"
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v4

      - name: Install yq
        run: |
          go install github.com/mikefarah/yq/v4@latest
          yq --version

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Check dependencies and open PRs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./.github/scripts/check-dependencies.sh
